# 1.Đại số tuyến tính

## 1.1 Số vô hướng
- Số vô hướng: hằng số có 1 giá trị cụ thể
- Biến số: biến x, y,... có thể nhận nhiều giá trị
- VD: y = a*x + b

In [2]:
import  numpy as np
import matplotlib.pyplot as plt

a = np.array(20)
b = np.array(200)


## 1.2 Vector
- Là tập hợp nhiều giá trị số vô hướng
- Biểu diễn đại lượng cụ thể (VD: diện tích nhà, số phòng ngủ)
- Khởi tạo bằng torch.tensor([...])
- Hoặc np.aray([...])

In [3]:
#numpy
x = np.array([1, 1.2, 1.5, 1.8, 2])
y = np.array([3.1, 4.3, 1.8, 2.3, 5])
#tensor
# x = torch.tensor([1, 1.2, 1.5, 1.8, 2])

- Các thuộc tính cơ bản

In [4]:
# Độ dài
print("length of vector: ", x.shape) # or len(x)

# Định dạng của véc tơ
print("vector type: ", x.dtype)

# Tổng của các phần tử 
print("sum of vector: ", x.sum())

# Trung bình các phần tử
print("mean of vector: ", x.mean())

# Giá trị nhỏ nhất
print("min of vector: ", x.min())

# Giá trị lớn nhất
print("max of vector: ", x.max())

length of vector:  (5,)
vector type:  float64
sum of vector:  7.5
mean of vector:  1.5
min of vector:  1.0
max of vector:  2.0


- Các phép tính

In [5]:
x = np.array([1, 1.2, 1.5, 1.8, 2])
y = np.array([3.1, 4.3, 1.8, 2.3, 5])
#Hai vector cung do dai
print(x+y)
print(x-y)
print(x*y)
print(x/y)
#Vector voi mot so vo huong
print(x+5)
print(x-5)
print(x*2)


[4.1 5.5 3.3 4.1 7. ]
[-2.1 -3.1 -0.3 -0.5 -3. ]
[ 3.1   5.16  2.7   4.14 10.  ]
[0.32258065 0.27906977 0.83333333 0.7826087  0.4       ]
[6.  6.2 6.5 6.8 7. ]
[-4.  -3.8 -3.5 -3.2 -3. ]
[2.  2.4 3.  3.6 4. ]


## 1.3 Ma trận

- Là mảng gồm nhiều vector, mõio vector ứng với một hàng
- A[i][j] là phần tử hàng i, cột j

### 1.3.1 Các ma trận đặc biệt

- Ma trận vuông: số hàng = số cột, khi tìm nghiệm, từ ma trận vuông -> chuyển sang ma trận tam giác, tính được định thức
- Ma trận đơn vị: ma trận vuông có đường chéo chính = 1, còn lại = 0
- Ma trận chuyển vị: B là chuyển vị của A khi cột của A ứng với hàng của B

### 1.3.2 Các thuộc tính của ma trận

In [6]:
import numpy as np
A = np.array([[1, 2, 3], 
              [3, 2, 1]])

# shape của matrix A
A.shape

(2, 3)

### 1.3.3 Các phép tính trên ma trận

In [9]:
import numpy as np
A = np.array([[1, 2, 3], 
              [3, 2, 1]])

B = np.array([[2, 1, 2], 
             [1, 3, 0]])

A+B     #Cộng ma trận
A-B     #Trừ ma trận
A*B     #Tích Hadamard (nhân từng phần tử)
# A@B     #Tích ma trận thường

array([[2, 2, 6],
       [3, 6, 0]])

### 1.3.4 Ma trận nghịch đảo
- Ma trận vuông B là ma trận nghịch đảo của A <=> A.B = I
- Khi đó: A khả nghịch (không suy biến); B (hay A^-1) là ma trận nghịch đảo của A
- Nếu AB = I thì: det(AB)=det(I) <-> det(A).det(B)=1
- det là định thức => tính khả nghịch của ma trận

### 1.3.5 Truy cập thành phần
- :n    => n index đầu tiên
- -n:   => n index cuối cùng
- i:j   => index từ i đến j-1
- ::k   => các index cách nhau k (chia hết cho k)
- :     => toàn bộ index

In [16]:
#VD truy cập vector con dòng 1 và 2 cột cuối cùng
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(A[1, -2:])

#Truy cập dòng cụ thể
print(A[[0,2], :])

[5 6]
[[1 2 3]
 [7 8 9]]


## 1.4 Tensor

### 1.4.1 **Tóm tắt về Tensor:**

1. **Định nghĩa:**
- Là định dạng đặc biệt do Google sáng tạo
- Tổng quát hơn ma trận, có thể biểu diễn không gian nhiều chiều

2. **Ứng dụng trong xử lý ảnh:**
- Kích thước ảnh: W × H × C
  - W: width (chiều rộng)
  - H: height (chiều cao) 
  - C: channels (kênh màu)
    - C = 1: ảnh xám
    - C = 3: ảnh màu RGB

3. **Trong huấn luyện mô hình:**
- Thêm chiều batch_size (N)
- Kích thước input: N × W × H × C
  - N: số lượng ảnh trong một mini-batch
  - W: chiều rộng
  - H: chiều cao
  - C: số kênh màu

In [19]:
# 1. Khởi tạo array 3 chiều
A = np.array([[[1, 2, 3], 
              [3, 2, 1]],
              [[2, 1, 2], 
              [1, 3, 0]]])

A[0] = [[1, 2, 3],   # Ma trận thứ nhất
        [3, 2, 1]]

A[1] = [[2, 1, 2],   # Ma trận thứ hai
        [1, 3, 0]]

# 2. Kiểm tra kích thước
print("shape of A: ", A.shape)  # Output: (2, 2, 3)
# Giải thích shape (2, 2, 3):
# - Chiều 0: 2 ma trận
# - Chiều 1: mỗi ma trận có 2 dòng
# - Chiều 2: mỗi dòng có 3 cột

# 3. Số chiều của array
print("total dim: ", A.ndim)  # Output: 3
# Giải thích ndim = 3:
# - Array có 3 chiều: [ma trận][dòng][cột]

# 4. Kiểu dữ liệu
print("dtype: ", A.dtype)  # Output: int64
# Giải thích dtype:
# - Các phần tử trong array là số nguyên
# - int64: số nguyên 64-bit

shape of A:  (2, 2, 3)
total dim:  3
dtype:  int64


### 1.4.2 **Tóm tắt về Phép tính và Truy cập Tensor:**

1. **Phép tính giữa Tensors:**
- Tích thông thường (@):
  - A[m,n,p] @ B[n,p,q] = C[m,n,q]
  - Sử dụng ký hiệu: A @ B

- Tích Hadamard (*):
  - Tensors phải cùng kích thước
  - Nhân từng phần tử tương ứng
  - Sử dụng ký hiệu: A * B

- Phép cộng/trừ (+/-):
  - Tensors phải cùng kích thước
  - Cộng/trừ từng phần tử tương ứng

2. **Truy cập phần tử:**
- Cú pháp: A[i,j,k] hoặc A[i][j][k]
  - i: chỉ số chiều thứ nhất
  - j: chỉ số chiều thứ hai
  - k: chỉ số chiều thứ ba

- Ví dụ truy cập:
  - A[:1, :, :] : ma trận đầu tiên
  - A[0][1:3, :] : dòng 1-2 của ma trận đầu
  - A[:1, :2, 3] : phần tử cụ thể theo 3 chiều

In [22]:
import numpy as np

# Tạo ma trận A(2,2,3)
# 2: Số lớp ma trận
# 2: Số hàng trong 1 lớp ma trận
# 3: Số cột trong một lớp ma trận
A = np.array([[[1, 2, 3],
               [4, 5, 6]],
              
              [[7, 8, 9],
               [10, 11, 12]]])

# Tạo ma trận B(2,3,2) để có thể nhân với A
B = np.array([[[1, 2],
               [3, 4],
               [5, 6]],
              
              [[7, 8],
               [9, 10],
               [11, 12]]])

# Tích A @ B
C = A @ B
print("Shape của C:", C.shape)  #(2,2,2)
print("\nKết quả C:")           #2lop@2lop => 2
print(C)                        #[2,3]@[3,2] => [2,2]

Shape của C: (2, 2, 2)

Kết quả C:
[[[ 22  28]
  [ 49  64]]

 [[220 244]
  [301 334]]]


## 1.5 Tích ma trận với vector

**Tích giữa Ma trận và Véc tơ:**

1. **Định nghĩa:**
- Là phép biến hình từ không gian n chiều sang m chiều
- Ma trận A ∈ ℝᵐˣⁿ, véc tơ x ∈ ℝⁿ
- Kết quả y = Ax ∈ ℝᵐ

2. **Công thức:**
Ax = [a₁ᵀ]    [a₁ᵀx]   [y₁]
     [a₂ᵀ] x = [a₂ᵀx] = [y₂] = y
     [...]    [...]    [...]
     [aₘᵀ]    [aₘᵀx]   [yₘ]

3. **Ứng dụng:**
- Machine Learning: Giảm chiều dữ liệu trong fully connected layers
- Phân tích suy biến (singular decomposition)
- Phép xoay (rotation) trong không gian
- Hồi qui tuyến tính: y = Xᵀw

4. **Ví dụ trong Python:**

In [24]:
import numpy as np

# 1. Tạo ma trận A (2x3)
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# 2. Tạo véc tơ x (3x1)
x = np.array([[1],
              [2],
              [3]])

# 3. Tính tích Ax
y = A @ x
print("\nKết quả y = Ax:\n", y)
print("Shape của y:", y.shape)  # (2,1)


Kết quả y = Ax:
 [[14]
 [32]]
Shape của y: (2, 1)


## 1.6 Tích vô hướng

**Tích Vô Hướng (Inner Product):**

1. **Định nghĩa:**
- Tích vô hướng giữa hai véc tơ x, y ∈ ℝᵈ
- Ký hiệu: ⟨x,y⟩ hoặc xᵀy
- Công thức: ⟨x,y⟩ = Σᵢ₌₁ᵈ xᵢyᵢ

2. **Cách tính trong Python:**
- x.dot(y)

3. **Ứng dụng:**
- Hồi qui tuyến tính: 
  - y = 20x₁ + 10x₂ + 200
  - ŷ = xᵀw với w = (20, 10, 200)

- Tính trung bình có trọng số:
  - x̄ = Σᵢ₌₁ⁿ xᵢqᵢ = xᵀq
  - với Σᵢ₌₁ⁿ qᵢ = 1

- Tính cos giữa hai véc tơ:
  - cos(x,y) = ⟨x,y⟩/(||x||₂||y||₂)
  - ||x||₂: norm chuẩn bậc 2

**Norm Chuẩn (Vector Norm):**

1. **Định nghĩa:**
- Là độ đo độ lớn (magnitude) của véc tơ
- Thường dùng nhất là norm chuẩn bậc 2 (L2 norm)
- Ký hiệu: ||x||₂ hoặc ||x||

2. **Các loại norm phổ biến:**
- L1 norm: ||x||₁ = Σ|xᵢ| (tổng giá trị tuyệt đối)
- L2 norm: ||x||₂ = √(Σxᵢ²) (căn bậc 2 tổng bình phương)
- L∞ norm: ||x||∞ = max|xᵢ| (giá trị tuyệt đối lớn nhất)

**Một hàm f(x) được gọi là chuẩn nếu thỏa mãn 3 tính chất:**
- Tính chất scale: α f(x) = f(αx)
- Bất đẳng thức tam giác: f(x + y) ≤ f(x) + f(y)
- Tính chất không âm: f(x) ≥ 0

## 1.8 Định thức và các tính chất của định thức

**1. Định nghĩa:**
- Định thức của ma trận vuông A được ký hiệu là |A| hoặc det(A)
- Công thức: det(A) = Σ(sgn(σ)a₁σ₁a₂σ₂...aₙσₙ)
  (σ là hoán vị của n số tự nhiên đầu tiên)

**2. Các tính chất cơ bản:**
- Chỉ tồn tại với ma trận vuông
- det(A) = det(Aᵀ) 
- det(I) = 1
- Ma trận đường chéo: det = tích các phần tử trên đường chéo
- det(AB) = det(A)det(B)
- det(A⁻¹) = 1/det(A) với A khả nghịch
- det = 0 nếu có một dòng/cột toàn 0
- Đổi vị trí 2 dòng/cột thì det đổi dấu
- Cộng vào một dòng/cột tích của dòng/cột khác thì det không đổi
- det(αA) = αⁿdet(A) với A là ma trận nxn

**3. Ý nghĩa:**
- Xác định tính khả nghịch của ma trận
- Giải hệ phương trình tuyến tính
- Kiểm tra tính độc lập tuyến tính của hệ véc tơ

## 1.9 Tổ hợp tuyến tính và không gian sinh

**1. Định nghĩa:**
- Cho n véc tơ a₁, a₂,..., aₙ ∈ ℝᵐ
- Cho n hệ số k₁, k₂,..., kₙ là số vô hướng
- Tổ hợp tuyến tính là véc tơ: k₁a₁ + k₂a₂ + ... + kₙaₙ = b

**2. Biểu diễn dưới dạng ma trận:**
- A = [a₁, a₂..., aₙ] ∈ ℝᵐˣⁿ (ma trận có cột là các véc tơ aᵢ)
- k = [k₁, k₂,..., kₙ]ᵀ (véc tơ hệ số)
- Tổ hợp tuyến tính: Ak = b

**3. Ý nghĩa:**
- Biểu diễn một véc tơ b thông qua tổ hợp các véc tơ cơ sở
- Nền tảng cho không gian véc tơ và không gian sinh
- Ứng dụng trong giải hệ phương trình tuyến tính

## 1.10 Cơ sở của một không gian (Basic)

**1. Định nghĩa:**
- Hệ véc tơ {a₁, a₂,..., aₙ} trong không gian véc tơ V = ℝᵐ
- Được gọi là cơ sở (basis) khi thỏa mãn 2 điều kiện:
  - V trùng span(a₁,..., aₙ) (không gian sinh)
  - Hệ véc tơ a₁, a₂,..., aₙ độc lập tuyến tính

**3. Tính chất:**
- Mọi véc tơ trong không gian V đều có thể biểu diễn duy nhất 
  dưới dạng tổ hợp tuyến tính của các véc tơ cơ sở

**4. Ý nghĩa:**
- Xác định hệ tọa độ cho không gian véc tơ
- Cơ sở tối thiểu để sinh ra toàn bộ không gian
- Số véc tơ cơ sở = số chiều của không gian

## 1.11 Biến đổi hệ cơ sở của vector
**1. Véc tơ đơn vị trong không gian m chiều:**
- Ký hiệu: (e₁, e₂,..., eₘ)
- eᵢ: véc tơ có phần tử thứ i = 1, còn lại = 0
- Ví dụ: e₁ = (1,0,0), e₂ = (0,1,0), e₃ = (0,0,1)

**2. Phép nhân ma trận với véc tơ:**
- Ma trận A ∈ ℝᵐˣⁿ, véc tơ x ∈ ℝⁿ
- Ax = a⁽¹⁾x₁ + a⁽²⁾x₂ + ... + a⁽ᵐ⁾xₘ = y
- Trong đó:
  + a⁽ᵢ⁾: véc tơ cột thứ i của ma trận A
  + xᵢ: phần tử thứ i của véc tơ x
  + y: véc tơ kết quả biểu diễn qua các véc tơ cơ sở cột

## 1.12 Range & Null space
**1. Range của ma trận A ∈ ℝᵐˣⁿ:**
- Ký hiệu: R(A)
- Định nghĩa: R(A) = {y ∈ ℝᵐ : ∃x ∈ ℝⁿ, Ax = y}
- Là không gian sinh (span) của các cột ma trận A
- Số chiều = số lượng cột độc lập tuyến tính

**2. Null Space của ma trận A:**
- Ký hiệu: N(A)
- Định nghĩa: N(A) = {x ∈ ℝⁿ : Ax = 0}
- Là tập các véc tơ x làm cho Ax = 0
- Khi các cột độc lập tuyến tính: N(A) = {0}

**3. Mối quan hệ:**
- R(A) và N(A) là không gian con véc tơ
- Tính chất quan trọng: dim(R(A)) + dim(N(A)) = n
  (với n là số cột của ma trận A)

## 1.13 Hạng của ma trận
**1. Định nghĩa:**
- Ký hiệu: rank(A)
- Là số lượng lớn nhất các cột/dòng độc lập tuyến tính
- rank(A) = 0 khi và chỉ khi A là ma trận 0

**2. Các tính chất quan trọng:**
- rank(A) = rank(Aᵀ)
- rank(A) ≤ min(m,n) với A ∈ ℝᵐˣⁿ
- rank(AB) ≤ min(rank(A), rank(B))
- rank(A + B) ≤ rank(A) + rank(B)

**3. Bất đẳng thức Sylvester:**
- Cho A ∈ ℝᵐˣⁿ, B ∈ ℝⁿˣᵏ
- rank(A) + rank(B) - n ≤ rank(AB)

**4. Ý nghĩa:**
- Xác định số chiều của không gian sinh bởi các cột/dòng
- Đánh giá tính độc lập tuyến tính của ma trận
- Quan trọng trong phân tích SVD và giải hệ phương trình