# Numpy
là một thư viện Python cung cấp một đối tượng mảng đa chiều, các đối tượng dẫn xuất khác nhau (như mảng và ma trận được che) và một loạt các quy trình để thực hiện các thao tác nhanh trên mảng, bao gồm toán học, logic, thao tác hình dạng, sắp xếp, chọn, I/O , các phép biến đổi Fourier rời rạc, đại số tuyến tính cơ bản, các phép toán thống kê cơ bản, mô phỏng ngẫu nhiên và nhiều hơn nữa.

Cốt lõi của gói NumPy là đối tượng ```ndarray```.
(viết tắt của "N-dimensional array" - mảng nhiều chiều) là một cấu trúc dữ liệu cốt lõi trong thư viện NumPy của Python. Nó đại diện cho một mảng đa chiều, đồng nhất (các phần tử có cùng kiểu dữ liệu), và có kích thước cố định.

Đặc điểm chính của ndarray:
Đa chiều: ndarray có thể có một hoặc nhiều chiều. Ví dụ:

1D: Mảng một chiều (vector).

2D: Mảng hai chiều (ma trận).

3D hoặc nhiều hơn: Mảng nhiều chiều.

Đồng nhất: Tất cả các phần tử trong ndarray phải có cùng kiểu dữ liệu (ví dụ: số nguyên, số thực, boolean, v.v.).

Hiệu suất cao: ndarray được tối ưu hóa để thực hiện các phép toán số học nhanh chóng và hiệu quả.

Hỗ trợ nhiều phép toán: NumPy cung cấp nhiều hàm để thao tác với ndarray, như phép toán số học, đại số tuyến tính, thống kê, v.v.

### Installation
Conda
```bash
# Best practice, use an environment rather than install in the base env
conda create -n my-env
conda activate my-env
# If you want to install from conda-forge
conda config --env --add channels conda-forge
# The actual install command
conda install numpy
```
Pip
```bash
pip install numpy
```

In [1]:
import numpy as np
import pandas as pd

# 1. Khởi tạo một mảng trên numpy
## 1.1. Khởi tạo ngay từ đầu
```python
np.array()
```
- có thể định dạng dữ liệu cụ thể như float, interger, boolean, string.
- phải đồng nhất về định dạng dữ liệu.

In [3]:
arr = np.array([1, 2, 3, 4, 5], dtype = np.float32)
print("Mảng khởi tạo từ đầu:", arr, "\ndtype:", arr.dtype)

Mảng khởi tạo từ đầu: [1. 2. 3. 4. 5.] 
dtype: float32


In [4]:
choices = np.random.choice(arr, size=3, replace=False)
print(choices)
randn_values = np.random.randn(2, 3)
print(randn_values)

normal_values = np.random.normal(loc=1, scale=2, size=(2, 3))
print(normal_values)

uniform_values = np.random.uniform(low=-1, high=1, size=(2, 3))
print(uniform_values)

randint_values = np.random.randint(low=-5, high=5, size=(2, 3))
print(randint_values)

[2. 4. 1.]
[[-0.71120789  1.17169118  0.22297736]
 [ 1.46205003 -0.00342217  1.5903156 ]]
[[ 1.29445407  0.83169785 -2.25045437]
 [ 0.89939018  2.53627699 -3.9925936 ]]
[[ 0.5450907  -0.50358821  0.47659403]
 [-0.78125398 -0.38073042  0.22276298]]
[[ 1 -1 -1]
 [ 0  1  2]]


# 2. Đọc và lưu numpy array từ file

In [5]:
arr = np.random.randint(low=-5, high=5, size=(4, 5))

In [6]:
#Save numpy
print("arr:", arr)
np.save("arr_saved.npy", arr)
np.savetxt("arr_saved.txt", arr)
print("Đã lưu arr vào arr_saved.npy và arr_saved.txt")

arr: [[-3  1 -2 -5 -3]
 [ 2  3  4 -2 -3]
 [ 2  2  0 -4  2]
 [-2  2  3  3 -2]]
Đã lưu arr vào arr_saved.npy và arr_saved.txt


In [7]:
# Load numpy
arr_loaded_npy = np.load("arr_saved.npy")
print("arr_loaded_npy:", arr_loaded_npy)
arr_loaded_txt = np.loadtxt("arr_saved.txt")
print("arr_loaded_txt:", arr_loaded_txt)

arr_loaded_npy: [[-3  1 -2 -5 -3]
 [ 2  3  4 -2 -3]
 [ 2  2  0 -4  2]
 [-2  2  3  3 -2]]
arr_loaded_txt: [[-3.  1. -2. -5. -3.]
 [ 2.  3.  4. -2. -3.]
 [ 2.  2.  0. -4.  2.]
 [-2.  2.  3.  3. -2.]]


In [8]:
# Convert array from dataframe
df_from_arr = pd.read_csv("arr_saved.txt", header=None, sep=" ")
arr_from_df = df_from_arr.values
print("arr_from_df:", arr_from_df)

arr_from_df: [[-3.  1. -2. -5. -3.]
 [ 2.  3.  4. -2. -3.]
 [ 2.  2.  0. -4.  2.]
 [-2.  2.  3.  3. -2.]]


In [9]:
# Ví dụ truy cập mảng
print("Phần tử thứ 2 của arr_loaded_npy:", arr_loaded_npy[1])
print("Dải phần tử từ 1 đến 3 của arr_loaded_npy:", arr_loaded_npy[1:4])

Phần tử thứ 2 của arr_loaded_npy: [ 2  3  4 -2 -3]
Dải phần tử từ 1 đến 3 của arr_loaded_npy: [[ 2  3  4 -2 -3]
 [ 2  2  0 -4  2]
 [-2  2  3  3 -2]]


# 3. Thay đổi shape của mảng
## 3.1. Reshape
```python
np.reshape()
```
Reshape mảng\nChúng ta có thể thay đổi shape cho mảng dựa vào câu lệnh np.reshape(). Hàm này vừa là một thuộc tính sẵn có trong mỗi mảng (tức là với ma trận A ta có thể gọi A.reshape()) vừa là hàm của numpy.\n

In [11]:
# Ví dụ về reshape mảng
B = np.array(np.arange(16))
print("B: \n", B)
print("B.shape: ", B.shape)


print(B.reshape(4, 4))


print(np.reshape(B, (4, 4)))


print(B.reshape(2, -1))

B = np.reshape(B, (2, -1))
print("B sau khi reshape:")
print(B)

B: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
B.shape:  (16,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
B sau khi reshape:
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


## 3.2. Chuyển vị các chiều
```python
np.transpose()
```
Chuyển vị các chiều\nChuyển vị các chiều của mảng là một trong những phép biến đổi cơ bản nhất mà chúng ta có thể thực hiện trên mảng. Để chuyển vị mảng, chúng ta có thể sử dụng hàm np.transpose().\n

In [12]:
# Image numpy example
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

img = mpimg.imread('logo_gpt.png')

print("img.shape:", img.shape)

img.shape: (1013, 1011, 4)


In [13]:
#transpose
img = img.transpose(2, 0, 1)
print("img.shape sau khi transpose:", img.shape)

img.shape sau khi transpose: (4, 1013, 1011)


## 3.3. Concatenate và Stack hai mảng

In [14]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_arr = np.concatenate((arr1, arr2))
stacked_arr = np.stack((arr1, arr2))
print("Mảng đã concatenate:", concatenated_arr)
print("Mảng đã stack:", stacked_arr)

Mảng đã concatenate: [1 2 3 4 5 6]
Mảng đã stack: [[1 2 3]
 [4 5 6]]


## 3.4. Mở rộng mảng

In [15]:
arr = np.load("arr_saved.npy")
arr

array([[-3,  1, -2, -5, -3],
       [ 2,  3,  4, -2, -3],
       [ 2,  2,  0, -4,  2],
       [-2,  2,  3,  3, -2]])

In [16]:
expanded_arr = np.expand_dims(arr, axis=0)
print("Mảng đã mở rộng:", expanded_arr)
print("Số shape của mảng ban đầu:", arr.shape)
print("Số shape của mảng đã mở rộng:", expanded_arr.shape)

Mảng đã mở rộng: [[[-3  1 -2 -5 -3]
  [ 2  3  4 -2 -3]
  [ 2  2  0 -4  2]
  [-2  2  3  3 -2]]]
Số shape của mảng ban đầu: (4, 5)
Số shape của mảng đã mở rộng: (1, 4, 5)


# 4. Các hàm trên numpy

In [17]:
# 3.4.1. min, max, mean, sum
print("Giá trị nhỏ nhất:", np.min(arr))
print("Giá trị lớn nhất:", np.max(arr))
print("Trung bình:", np.mean(arr))
print("Tổng:", np.sum(arr))

# 3.4.2. minimum, maximum
arr3 = np.array([10, 20, 30])
arr4 = np.array([5, 25, 15])
print("Phần tử nhỏ nhất giữa hai mảng:", np.minimum(arr3, arr4))
print("Phần tử lớn nhất giữa hai mảng:", np.maximum(arr3, arr4))

# 3.4.3. argmax, argmin
print("Vị trí giá trị lớn nhất:", np.argmax(arr))
print("Vị trí giá trị nhỏ nhất:", np.argmin(arr))

Giá trị nhỏ nhất: -5
Giá trị lớn nhất: 4
Trung bình: -0.1
Tổng: -2
Phần tử nhỏ nhất giữa hai mảng: [ 5 20 15]
Phần tử lớn nhất giữa hai mảng: [10 25 30]
Vị trí giá trị lớn nhất: 7
Vị trí giá trị nhỏ nhất: 3


In [18]:
# argsort
print("Vị trí các phần tử khi sắp xếp:", np.argsort(arr))

# np.exp() và hàm softmax
exp_arr = np.exp(arr)
softmax_arr = exp_arr / np.sum(exp_arr)
print("Mảng sau khi sử dụng np.exp():", exp_arr)
print("Mảng sau khi sử dụng softmax:", softmax_arr)

# Giữ nguyên shape
print("Mảng giữ nguyên shape sau khi cộng với scalar:", arr + 1)

# Gieo hạt và trộn lẫn dữ liệu trên numpy
np.random.seed(0)
shuffled_arr = np.random.permutation(arr)
print("Mảng đã trộn lẫn:", shuffled_arr)

Vị trí các phần tử khi sắp xếp: [[3 0 4 2 1]
 [4 3 0 1 2]
 [3 2 1 0 4]
 [0 4 1 2 3]]
Mảng sau khi sử dụng np.exp(): [[4.97870684e-02 2.71828183e+00 1.35335283e-01 6.73794700e-03
  4.97870684e-02]
 [7.38905610e+00 2.00855369e+01 5.45981500e+01 1.35335283e-01
  4.97870684e-02]
 [7.38905610e+00 7.38905610e+00 1.00000000e+00 1.83156389e-02
  7.38905610e+00]
 [1.35335283e-01 7.38905610e+00 2.00855369e+01 2.00855369e+01
  1.35335283e-01]]
Mảng sau khi sử dụng softmax: [[3.18669708e-04 1.73987765e-02 8.66234077e-04 4.31272552e-05
  3.18669708e-04]
 [4.72947781e-02 1.28560536e-01 3.49463769e-01 8.66234077e-04
  3.18669708e-04]
 [4.72947781e-02 4.72947781e-02 6.40065219e-03 1.17232034e-04
  4.72947781e-02]
 [8.66234077e-04 4.72947781e-02 1.28560536e-01 1.28560536e-01
  8.66234077e-04]]
Mảng giữ nguyên shape sau khi cộng với scalar: [[-2  2 -1 -4 -2]
 [ 3  4  5 -1 -2]
 [ 3  3  1 -3  3]
 [-1  3  4  4 -1]]
Mảng đã trộn lẫn: [[ 2  2  0 -4  2]
 [-2  2  3  3 -2]
 [ 2  3  4 -2 -3]
 [-3  1 -2 -5 -3]]


# 3.5. Các ma trận đặc biệt

In [20]:
# Ma trận đơn vị
identity_matrix = np.eye(3)
print("Ma trận đơn vị 3x3:\n", identity_matrix)

# Ma trận 1
ones_matrix = np.ones((3, 3))
print("Ma trận 1 3x3:\n", ones_matrix)

# Ma trận 0
zeros_matrix = np.zeros((3, 3))
print("Ma trận 0 3x3:\n", zeros_matrix)

# Ma trận đường chéo chính
diagonal_matrix = np.diag([1, 2, 3])
print("Ma trận đường chéo chính:\n", diagonal_matrix)

Ma trận đơn vị 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Ma trận 1 3x3:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Ma trận 0 3x3:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ma trận đường chéo chính:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


# 3.6. Các phép toán trên ma trận

In [21]:
# Phép chuyển vị
matrix = np.array([[1, 2], [3, 4]])
transposed_matrix = matrix.T
print("Ma trận đã chuyển vị:", transposed_matrix)

# Ma trận nghịch đảo
inverse_matrix = np.linalg.inv(matrix)
print("Ma trận nghịch đảo:", inverse_matrix)

# Hạng ( rank ) của ma trận.
rank_matrix = np.linalg.matrix_rank(matrix)
print("Hạng của ma trận:", rank_matrix)

# Định thức ( determinant ) của ma trận
determinant_matrix = np.linalg.det(matrix)
print("Định thức của ma trận:", determinant_matrix)

# Trace của ma trận
trace_matrix = np.trace(matrix)
print("Trace của ma trận:", trace_matrix)

# Chuẩn Frobenious
frobenius_norm = np.linalg.norm(matrix, 'fro')
print("Chuẩn Frobenious của ma trận:", frobenius_norm)

Ma trận đã chuyển vị: [[1 3]
 [2 4]]
Ma trận nghịch đảo: [[-2.   1. ]
 [ 1.5 -0.5]]
Hạng của ma trận: 2
Định thức của ma trận: -2.0000000000000004
Trace của ma trận: 5
Chuẩn Frobenious của ma trận: 5.477225575051661


In [22]:
# Các phép cộng, trừ
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
added_matrix = matrix1 + matrix2
subtracted_matrix = matrix1 - matrix2
print("Ma trận sau khi cộng:", added_matrix)
print("Ma trận sau khi trừ:", subtracted_matrix)

# Phép nhân ma trận thông thường
multiplied_matrix = np.dot(matrix1, matrix2)
print("Ma trận sau khi nhân:", multiplied_matrix)

# Tích Hadamard (element-wise product) giữa hai ma trận
hadamard_product = np.multiply(matrix1, matrix2)
print("Tích Hadamard giữa hai ma trận:", hadamard_product)

# Nhân ma trận với một véc tơ
vector = np.array([1, 2])
multiplied_vector = np.dot(matrix1, vector)
print("Ma trận sau khi nhân với véc tơ:", multiplied_vector)

# Nhân ma trận với một scaler
scaled_matrix = matrix1 * 2
print("Ma trận sau khi nhân với scaler:", scaled_matrix)

Ma trận sau khi cộng: [[ 6  8]
 [10 12]]
Ma trận sau khi trừ: [[-4 -4]
 [-4 -4]]
Ma trận sau khi nhân: [[19 22]
 [43 50]]
Tích Hadamard giữa hai ma trận: [[ 5 12]
 [21 32]]
Ma trận sau khi nhân với véc tơ: [ 5 11]
Ma trận sau khi nhân với scaler: [[2 4]
 [6 8]]


# 3.8. Các phép toán trên véc tơ

In [23]:
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
dot_product = np.dot(vector1, vector2)
print("Tích vô hướng giữa hai véc tơ:", dot_product)

Tích vô hướng giữa hai véc tơ: 32
